command:
  - venv\Scripts\python.exe
  - ${program}
  - ${args}
program: ergebnisse_chapter_runner\runnerDirectControlSimBasicConfigWandB.py
method: grid
parameters:
  placeholder:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5

